version: "3"

services: 
  app:
    build: ./app
    volumes: 
      - ./app:/var/www/html
      - ./app/000-default.conf:/etc/apache2/sites-available/000-default.conf
    working_dir: 
      /var/www/html
    ports: 
      - 8080:80
    links: 
      - database

  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - ./db-volume:/var/lib/mysql

  databasemanager:
    image: phpmyadmin/phpmyadmin
    ports:
      - 5000:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - database